Initial version of the give_total_forms shortcode
impress-org/givewp-snippet-library pull request #137
Opened 2022-06-17 14:30 UTC by matheuswd

This is an initial version of the custom shortcode that checks how many donation forms are published and allows the admin to select to which page the donor will be redirected to select the donation form they want to donate to.

2022-06-29 20:18 UTC, jonwaldstein requested changes
@matheuswd nice job! just wanted to make a suggestion to change the `donation_forms_page` argument to an ID.

2022-06-29 20:18 UTC, jonwaldstein commented on custom-shortcodes/give-total-forms.php
> +	}
```suggestion
	if ( $atts['donation_forms_page_id']) {
        	$link = get_permalink($atts['donation_forms_page_id']);
        	
		$donation_forms_page = '<a href="' . $link . '"> Check out our campaigns! <a>';	
	}
```

2022-06-29 20:18 UTC, jonwaldstein commented on custom-shortcodes/give-total-forms.php
> +		'donation_forms_page' => false,
```suggestion
		'donation_forms_page_id' => false,
```

2022-06-29 20:18 UTC, jonwaldstein commented on custom-shortcodes/give-total-forms.php
> +	}
@matheuswd I would suggest getting the permalink from the id so the link is dynamic.

2022-06-29 20:18 UTC, jonwaldstein commented on custom-shortcodes/give-total-forms.php
> +		'donation_forms_page' => false,
@matheuswd I would suggest changing this to an ID so it's more clear & we can make the link dynamic

2022-07-27 16:56 UTC, matheuswd reviewed
👍

2022-07-27 17:59 UTC, jonwaldstein approved these changes
Great job!

2022-08-09 13:54 UTC, merged