Shortcodes/donations form a form shortcode
impress-org/givewp-snippet-library pull request #140
Opened 2022-07-27 17:15 UTC by matheuswd

2022-08-04 14:11 UTC, jonwaldstein requested changes
Hey @matheuswd great first pass! This definitely works but I added some comments and suggestions to improve upon what you have.

2022-08-04 14:11 UTC, jonwaldstein commented on custom-shortcodes/donations-for-a-form-shortcode.php
> +		return $html;
I'm seeing this html structure consistently for all your conditions.  The only difference is the content inside the `<p>` tag.  To make this whole function more [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) I would suggest doing all your conditionals inside one instance of the html.

something like this...
```
$atts = shortcode_atts(array(
    'form_id' => false,
), $atts, 'give_raised_for_forms');

$formId = $atts['form_id'];

if (!$formId) {
    $message = 'It\'s necessary that you insert the form ID on the shortcode.';
} elseif (get_post_type($formId) !== 'give_forms') {
    $message = 'This is not a donation form. Make sure you are using an ID for a donation form.';
} else {
    $form_title = get_the_title($formId);
    $number_of_donations = give_get_meta($formId, '_give_form_sales', true);

    $message = sprintf(
        'We already have %s donations for the %s campaign!',
        $number_of_donations,
        $form_title
    );
}

return '<div class="give_raised_for_forms"><p> ' . $message . '</p></div>';
```

2022-08-04 14:11 UTC, jonwaldstein commented on custom-shortcodes/donations-for-a-form-shortcode.php
> +	$number_of_donations = $info[ '_give_form_sales' ][0];
You can simplify this with `$number_of_donations = give_get_meta($formId, '_give_form_sales', true);`

2022-08-08 17:22 UTC, matheuswd commented on custom-shortcodes/donations-for-a-form-shortcode.php
> +	if ( ! $atts[ 'form_id' ] ) {
It makes total sense. Thanks

2022-08-08 17:23 UTC, matheuswd commented on custom-shortcodes/donations-for-a-form-shortcode.php
> +		<div class="give_total_forms">
👍

2022-08-08 17:23 UTC, matheuswd commented on custom-shortcodes/donations-for-a-form-shortcode.php
> +		return $html;
Much better!

2022-08-08 17:23 UTC, matheuswd commented on custom-shortcodes/donations-for-a-form-shortcode.php
> +	$number_of_donations = $info[ '_give_form_sales' ][0];
thanks! I've never used this so it's learning opportunity.

2022-08-08 17:25 UTC, matheuswd commented
@jonwaldstein I've reviewed everything and I think it's ok nw. Can you review it?

2022-08-08 17:50 UTC, jonwaldstein approved these changes
@matheuswd great job!

2022-08-09 13:54 UTC, merged